name: Auto Update README

on:
  workflow_dispatch:
  schedule:
    - cron: '0 12 * * *'

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Update README.md
        run: |
          echo "# Hello DevOps" > README.md
          echo "" >> README.md
          echo "![CI](https://github.com/Pityukasdhun/hello-devops/actions/workflows/docker-build.yml/badge.svg)" >> README.md
          echo "" >> README.md
          echo "Automatikus frissítés: $(date)" >> README.md

      - name: Commit and Push README.md
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git add README.md
          git commit -m "docs: auto update README on schedule"
          git push
